# Generated by Django 4.2.4 on 2023-08-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='birthday',
            field=models.DateField(blank=True, default='', verbose_name='birthday'),
        ),
    ]
