# Generated by Django 4.2.4 on 2023-08-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_baseuser_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='birthday',
            field=models.DateField(verbose_name='birthday'),
        ),
    ]
