# Generated by Django 4.2.4 on 2023-08-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driverapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverlog',
            name='day',
            field=models.DateField(default='1800-01-01', verbose_name='time now with status'),
        ),
        migrations.AddField(
            model_name='driverlog',
            name='time',
            field=models.SmallIntegerField(default=0, verbose_name='count ours with status'),
        ),
    ]
